---
title: "Figure 4b - Draft"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width=8, fig.height=7)
```

### Fig 4b

 
```{r}
# SETUP
library(tidyverse)
library(ggcorrplot)
setwd(dir = "~/PD/Data/OoL/38_Draft_4/_fig4/_b/")
theme_set(theme_classic(base_size=24))


### Load data
# coacervate data
master_coac <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/19.1_Draft_2/Generate_input/draft2_input.RDS")
# fus data
master_fus <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/22_FUS_sequencing_1/_1_data_prep/master.RDS")
# dhh1 data
master_dhh1 <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/24_2_Dhh1_repeat/_1_data_prep/master.RDS")
# Bad FUS data
master_fus2 <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/23_FUS_sequencing_2/_1_data_prep/master.RDS")


### Format data
# add information about droplet type
master_coac <- master_coac %>% 
  mutate(droplet_type = if_else(experiment == "ool17" | experiment == "ool18", "pdda", 
                                if_else(experiment == "ool17_input" | experiment == "ool18_input" | experiment == "ool12_input", "input", "lys")))

master_fus <- master_fus %>% 
  mutate(droplet_type = if_else(experiment == "ool22", "fus", "input"))

master_fus2 <- master_fus2 %>% 
  mutate(droplet_type = if_else(experiment == "ool23", "fus", "input"))

master_dhh1 <- master_dhh1 %>% 
  mutate(droplet_type = if_else(experiment == "ool24_2", "dhh1", "input"))
```

Add read-coverage information

```{r}
### ---- ool23 ----

# load coverage information from fus_bad
ool23_cov <- read.csv(file = "/Users/damian_wollny/PD/Data/OoL/31_mapping_artefact_issue/_samtools_depth/ool23_rel_coverage.csv", stringsAsFactors = F) %>% select(-X) %>% filter(V1 != "V1")

# Format ool23_cov
colnames(ool23_cov) <- c("cell_id", "target_id", "rel_coverage")
ool23_cov[,1] <- ool23_cov$cell_id %>% str_replace("_", ".")
ool23_cov[,1] <- ool23_cov$cell_id %>% str_replace("_", substr(ool23_cov$cell_id, 1, 2))
ool23_cov[,1] <- ool23_cov$cell_id %>% str_replace(substr(ool23_cov$cell_id, 1, 3), "")
ool23_cov$cell_id[ool23_cov$cell_id == "OOL23P2D1"] <- "OOL23INPUT"

master_fus2_plus <- 
  left_join(master_fus2, ool23_cov, by = c("cell_id", "target_id")) %>% 
  mutate(rel_coverage = as.numeric(rel_coverage))

### ---- ool12 ----

# load coverage information from Dhh1
ool12_cov <- read.csv(file = "/Users/damian_wollny/PD/Data/OoL/12_Another_attempt_to_increase_n/data/ool12_rel_coverage.csv", stringsAsFactors = F) %>% select(-X) %>% filter(V1 != "V1")

# Format ool12_cov
colnames(ool12_cov) <- c("cell_id", "target_id", "rel_coverage")

master_lys_plus <- 
  left_join(master_coac %>% filter(experiment == "ool12"), ool12_cov, by = c("cell_id", "target_id")) %>% 
  mutate(rel_coverage = as.numeric(rel_coverage))

### ---- ool24_2 ----

# load coverage information from Dhh1
ool24_2_cov <- read.csv(file = "/Users/damian_wollny/PD/Data/OoL/24_2_Dhh1_repeat/_kallisto_output/ool24_2_rel_coverage.csv", stringsAsFactors = F) %>% select(-X) %>% filter(V1 != "V1")

# Format ool24_2_cov
colnames(ool24_2_cov) <- c("cell_id", "target_id", "rel_coverage")
ool24_2_cov$cell_id[ool24_2_cov$cell_id == "OOL24V2P1H12"] <- "OOL24V2INPUT"

master_dhh1_plus <- 
  left_join(master_dhh1, ool24_2_cov, by = c("cell_id", "target_id")) %>% 
  mutate(rel_coverage = as.numeric(rel_coverage))
```

Integrate datasets and make read-coverage cutoff

```{r}
pre_master <- bind_rows(master_lys_plus, master_fus, master_dhh1_plus, master_fus2_plus, 
                        master_coac %>% filter(experiment %in% c("ool17", "ool17_input", "ool18", "ool18_input", "ool12_input"))) %>% 
  mutate(rel_coverage = if_else(droplet_type == "pdda", 1, rel_coverage)) %>% 
  mutate(rel_coverage = if_else(experiment == "ool22", 1, rel_coverage)) %>% 
  mutate(rel_coverage = if_else(droplet_type == "input", 1, rel_coverage))
master <- pre_master %>% filter(rel_coverage >= 0.2)
```

```{r, fig.width=10, fig.height=10}
# LYS data:
c_ool12 <- master %>% 
  filter(experiment == "ool12") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(ool12_percent = count*100/max(count)) %>% select(-count)

# PDDA data:
c_ool17 <- master %>% 
  filter(experiment == "ool17") %>%
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(ool17_percent = count*100/max(count)) %>% select(-count)

c_ool18 <- master %>% 
  filter(experiment == "ool18") %>%
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(ool18_percent = count*100/max(count)) %>% select(-count)

# FUS data:
c_ool22 <- master %>% 
  filter(experiment == "ool22") %>%
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(ool22_percent = count*100/max(count)) %>% select(-count)

# Dhh1 data:
c_ool24_2 <- master %>% 
  filter(experiment == "ool24_2") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(ool24_2_percent = count*100/max(count)) %>% select(-count)

# Combine all data
c_all <- full_join(c_ool12, c_ool17, by='target_id') %>% 
            full_join(., c_ool18, by='target_id') %>% 
              full_join(., c_ool22, by='target_id') %>% 
                full_join(., c_ool24_2, by='target_id') 

# Calculate average between replicates (PDDA)
c_all_sub <- c_all %>% drop_na() %>% 
  mutate(ave_pdda = (ool17_percent+ool18_percent)/2) %>% 
  select(-c(ool17_percent, ool18_percent)) %>% 
  rename("PDDA\nDroplets" = ave_pdda, "Dhh1\nDroplets" = ool24_2_percent, "FUS\nDroplets" = ool22_percent, "Lysine\nDroplets" = ool12_percent)

# convert to numeric for cor() function
c_all_sub_numeric <- sapply(c_all_sub[,c(2:5)], as.numeric)

# plot
plot(c_all_sub[,c(2:5)], pch = 21, lower.panel = NULL, cex.axis=2, cex.labels = 1.5)

```

```{r, echo=F}
# export plot
png("./fig4b_1.png", width = 7, height = 7, units = "in", res = 300)
plot(c_all_sub[,c(2:5)], pch = 21, lower.panel = NULL, cex.axis=2, cex.labels = 1.7)
dev.off()
```

```{r}
# generate correlation matrix
c_all_sub_cor <- cor(c_all_sub_numeric, method = "pearson")

# plot:
ggcorrplot(c_all_sub_cor, hc.order = TRUE, type = "lower", outline.col = "white", lab = T) +
  scale_fill_distiller(palette = "Spectral", limit = c(0.7,1), name = "Pearson\nCorrelation") 
```

```{r, echo = F}
corrplot <- ggcorrplot(c_all_sub_cor, hc.order = TRUE, type = "lower", outline.col = "white", lab = T) +
  scale_fill_distiller(palette = "Spectral", limit = c(0.7,1), name = "Pearson\nCorrelation") +
  theme_classic() +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.line = element_blank(), axis.ticks = element_blank()) 

ggsave(corrplot, file="./fig4b_2.pdf",width = 6, height = 6, device = "pdf")
```

