---
title: "Figure S1 - Draft"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = FALSE, message = FALSE)
options(width = 12)
```

```{r}
# Setup
library(tidyverse)
library(ggExtra)
theme_set(theme_classic(base_size=24))
setwd("~/PD/Data/OoL/43_Draft_5/_s_fig1/test")
```

### Motifs of enriched transcripts

```{r, fig.width=10, fig.height=7}
# Data:
facs_data <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/18.2_integrative_analysis/_8_coacervate_size_comp/master_facs.RDS")
fig1b_data_all.1 <- facs_data %>% filter(experiment == "ool17_noRNA") %>% mutate(condition = "noRNA")
fig1b_data_all.2 <- facs_data %>% filter(experiment == "ool17_RNA") %>% mutate(condition = "RNA")
fig1b_data_all <- bind_rows(fig1b_data_all.1, fig1b_data_all.2)

# Plot:
s_fig1b_plot <- ggplot(data = fig1b_data_all, aes(x = `FSC-A`, y = `SSC-A`, color = condition)) +
  geom_point(size = 2, color = "black", alpha = .3) +
  stat_smooth(alpha = .3, size = 1)  +
  facet_grid(. ~ condition) +
  scale_y_continuous(trans = "log10", expand = c(0,0)) +
  scale_x_continuous(trans = "log10") +
  theme(legend.position = "top", 
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = c("#9E0142", "darkgrey"), name = " ", labels = c("RNA", "no RNA")) +
  labs(y = "Coacervate granularity\n(SSC)", x = "Coacervate size\n(FSC)") 
plot(s_fig1b_plot)

ggsave(s_fig1b_plot, filename = "./s_fig1b_plot.pdf", width = 7, height = 6)
```

```{r}
master <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/19.1_Draft_2/Generate_input/draft2_input.RDS")

# --- OOL17 replicate ------------------
ool17_bens_plot <- master %>% 
  filter(tpm != 0) %>% 
  filter(experiment == "ool17") %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(count = replace(count, which(is.na(count)), 0)) %>% # include all transcripts that are found in 0 coac
  mutate(percent = count*100/max(count)) 

# --- OOL18 replicate ------------------
ool18_bens_plot <- master %>% 
  filter(tpm != 0) %>% 
  filter(experiment == "ool18") %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  mutate(count = replace(count, which(is.na(count)), 0)) %>% # include all transcripts that are found in 0 coac
  mutate(percent = count*100/max(count)) 

# --- Ave ------------------

# Filter all transcripts that are present in both replicate experiments
pre_ave_bens_plot <- inner_join(ool17_bens_plot, ool18_bens_plot, by = "target_id")

# Calc ave(input_tpm) and ave(percent) for each transcript
ave_bens_plot <- pre_ave_bens_plot %>% 
  mutate(percent = (percent.x+percent.y)/2) %>% 
  inner_join(.,master[,c(2,6)], by="target_id") %>% distinct() %>% 
  select(target_id, percent, length) 


s_fig1c <- ave_bens_plot %>% 
  ggplot(aes(x = length, y = percent, fill = percent) ) +
  geom_point(size = 2, alpha = .6, shape = 21) +
  scale_fill_distiller(palette = "Spectral") +
  scale_x_continuous(trans='log10') +
  labs(x = "Transcript length\n[bp]", y = "Detected in x\ncoacervates [%]") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

s_fig1c_plot <- ggMarginal(s_fig1c + theme(legend.position = "none"), type = "histogram", margins = "both",
           fill = "white", col = "black")

s_fig1c_plot

ggsave(s_fig1c_plot, filename = "./s_fig1c_plot.png", width = 6, height = 6)
```


```{r}
#
# ---- OOL17 Data ------------------------------------
#

# all coacervate rnas
ool17_all_coac_rnas <- master %>%  
  filter(experiment == "ool17") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(num_coac = n()) %>% 
  mutate(perc_coac = num_coac/max(num_coac)*100) %>% 
  arrange(desc(num_coac))

# input rnas + their presence in x # of coacervates
ool17_all_input_rnas <- master %>% 
  filter(experiment == "ool17_input") %>% 
  filter(tpm != 0) %>% 
  left_join(.,ool17_all_coac_rnas, by = "target_id") %>% 
  mutate(num_coac = replace_na(num_coac,0)) %>% 
  dplyr::select(target_id, num_coac, perc_coac) %>% 
  arrange(desc(num_coac)) 

ool17_input_plot <- ool17_all_input_rnas %>% left_join(.,master %>% filter(experiment == "ool17_input") %>% select(length, target_id, log2_tpm), by = "target_id") %>% distinct() %>% mutate(dataset = "Experiment 1") %>% mutate(in_condensates = "Yes")
ool17_input_zero <- ool17_all_input_rnas %>% filter(num_coac == 0) %>% left_join(.,master %>% filter(experiment == "ool17_input") %>% select(length, target_id, log2_tpm), by = "target_id") %>% distinct() %>% mutate(dataset = "Experiment 1") %>% mutate(in_condensates = "No")


#
# ---- OOL18 Data ------------------------------------
#

# all coacervate rnas
ool18_all_coac_rnas <- master %>%  
  filter(experiment == "ool18") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(num_coac = n()) %>% 
  mutate(perc_coac = num_coac/max(num_coac)*100) %>% 
  arrange(desc(num_coac))

# input rnas + their presence in x # of coacervates
ool18_all_input_rnas <- master %>% 
  filter(experiment == "ool18_input") %>% 
  filter(tpm != 0) %>% 
  left_join(.,ool18_all_coac_rnas, by = "target_id") %>% 
  mutate(num_coac = replace_na(num_coac,0)) %>% 
  dplyr::select(target_id, num_coac, perc_coac) %>% 
  arrange(desc(num_coac)) 

ool18_input_plot <- ool18_all_input_rnas %>% left_join(.,master %>% filter(experiment == "ool18_input") %>% select(length, target_id, log2_tpm), by = "target_id") %>% distinct() %>% mutate(dataset = "Experiment 2") %>% mutate(in_condensates = "Yes")
ool18_input_zero <- ool18_all_input_rnas %>% filter(num_coac == 0) %>% left_join(.,master %>% filter(experiment == "ool18_input") %>% select(length, target_id, log2_tpm), by = "target_id") %>% distinct() %>% mutate(dataset = "Experiment 2") %>% mutate(in_condensates = "No")

# --- combine datasets --- 
s_fig1d <- bind_rows(ool17_input_plot, ool17_input_zero, ool18_input_plot, ool18_input_zero)

# --- plot --- 
s_fig1d_plot <- ggplot(data = s_fig1d) +
  geom_boxplot(aes(x = dataset, y = log2_tpm, color = in_condensates)) +
  facet_grid(. ~ dataset, scales = "free_x") +
  scale_color_manual(values =  c("darkgrey", "#9E0142")) + 
  labs(y = "Input RNA: log2(TPM)") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.line.x = element_blank(), axis.title.x = element_blank(),
        legend.title = element_text(size = 18)) +
  labs(color = "Found in\nCondensates?")
s_fig1d_plot

ggsave(s_fig1d_plot, filename = "./s_fig1d_plot.pdf", width = 7, height = 6)
```

