---
title: "ool44: Partician Coefficients"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,fig.width= 12, fig.height=7)
```

```{r}
library(tidyverse)
library(data.table)
library(mgcv)
library(seqinr)

theme_set(theme_classic(base_size=22))
```

Orginal data (and analysis) can be found in:

/Users/damian_wollny/PD/Data/OoL/44_partition_coeff/

```{r}
# open data from image quantification

img_count <- read.csv(file = "~/PD/Data/OoL/44_partition_coeff/quantification.csv", sep = ";") %>% select(-n) %>% as.tbl()

# plot
partcoeff_plot <- img_count %>% 
  group_by(sample) %>% 
  mutate(part_coeff = ave/mean(ave[background == "yes"])) %>% 
  filter(background == "no",
         sample == "iPSC_RNA_5ngul_PI_1_1000_60min_2" ) %>% 
  ggplot(aes(x = sample, y = part_coeff, fill = sample)) +
  geom_boxplot() +
  geom_point(alpha = .7, size = 4, pch = 21) +
  #coord_flip() +
  labs(y = "Partition coefficient", x = "") +
  theme(legend.position = "none", axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.line.x = element_blank())

plot(partcoeff_plot)
print(paste("Number of droplets quantified:", 
            img_count %>% filter(background == "no", sample == "iPSC_RNA_5ngul_PI_1_1000_60min_2" ) %>% nrow()))

print(paste("Median Part Coeff:", 
            img_count %>% 
              group_by(sample) %>% 
              mutate(part_coeff = ave/mean(ave[background == "yes"])) %>% 
              filter(background == "no",
                     sample == "iPSC_RNA_5ngul_PI_1_1000_60min_2" ) %>% 
              pull(part_coeff) %>% 
              median()
            )
      )

```

```{r, eval=F}
ggsave(partcoeff_plot, file="~/PD/Data/OoL/43_Draft_5/_s_fig1/_coacervates/s_fig1_partcoef.pdf", width = 4, height = 6, device = "pdf")
```

