---
title: "Figure 2 - Follow up"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE)
```

```{r}
# Setup
library(tidyverse)
library(cowplot)
library(gridExtra)
theme_set(theme_classic(base_size=24))
setwd(dir = "~/PD/Data/OoL/38_Draft_4/_s_fig1/")
```

### Is there a linear relationship between the RNA isolated from 1000, 100, 10 or single condensates and can the quantified cDNA (post amplification) be a proxy for that?

```{r}
x <- c(64340.3,49921.4,7770.1,8006.3,2144.8,1691.1,275.1,272.8,235.1,327.3,78.5)
y <- c(1000,1000,100,100,10,10,1,1,1,1,0)

x_name <- "molarity"
y_name <- "num_coac"

bioanalyzer_data <- data.frame(x,y)
names(bioanalyzer_data) <- c(x_name,y_name)
bioanalyzer_data

model <- lm(num_coac ~ molarity, bioanalyzer_data) 
r2 <- summary(model)$r.squared

plot_1 <- ggplot(data = bioanalyzer_data, aes(x = (num_coac), y = molarity)) +
  geom_point() +
  geom_smooth(method = "lm") +
  annotate(geom = 'text', label = paste("R^2 = ", round(r2,2), sep=""), x = 12, y = 6e4, hjust = -.0, vjust = 0, size = 8) +
  labs(y = "Molarity [pM]", x = "Number of sorted coacervates")
plot_1

plot_2 <- bioanalyzer_data %>% 
  filter(num_coac < 10) %>% 
  ggplot(aes(x = as.factor(num_coac), y = molarity, fill = as.factor(num_coac))) +
  geom_boxplot(show.legend = F) + 
  geom_point(alpha = .7, size = 4, show.legend = F, pch = 21) +
  expand_limits(y = 0) +
  labs(y = "Molarity [pM]", x = "Number of\nsorted coacervates", title = "cDNA yield")
plot_2
```

```{r, eval=F}
# Export plots
ggsave(plot_1, file="./s_fig1_plot1.pdf", width = 6, height = 6, device = "pdf")
ggsave(plot_2, file="./s_fig1_plot2.pdf", width = 5, height = 6, device = "pdf")
```

