---
title: "Figure 2"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = FALSE, message = FALSE)
```

```{r}
# Setup
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(VennDiagram)

theme_set(theme_classic(base_size=20))
```

<style type="text/css">

body, td {
   font-size: 18px;
}
</style>

```{r}
# Load seq data
master <- readRDS(file = "../_input/coacervate_data.RDS")
```


```{r}
#
# ---- OOL17 Data ------------------------------------
#

# all coacervate rnas
ool17_all_coac_rnas <- master %>%  
  filter(experiment == "ool17") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(num_coac = n()) %>% 
  mutate(perc_coac = num_coac/max(num_coac)*100) %>% 
  arrange(desc(num_coac))

# input rnas + their presence in x # of condensates
ool17_all_input_rnas <- master %>% 
  filter(experiment == "ool17_input") %>% 
  filter(tpm != 0) %>% 
  left_join(.,ool17_all_coac_rnas, by = "target_id") %>% 
  mutate(num_coac = replace_na(num_coac,0)) %>% 
  dplyr::select(target_id, num_coac, perc_coac) %>% 
  arrange(desc(num_coac)) 

# How many input RNAs are in how many condensates?
ool17_all_input_rnas.2 <- ool17_all_input_rnas %>% 
  group_by(num_coac) %>% 
  summarise(num_transcripts = n())

# As in 'all_input_rnas.2' but in %
ool17_all_input_rnas.3 <- ool17_all_input_rnas %>% 
  left_join(.,ool17_all_input_rnas.2, by = "num_coac") %>% 
  mutate(perc_transcripts = num_transcripts/nrow(.)*100) %>% 
  dplyr::select(perc_coac, perc_transcripts) %>% distinct() %>% 
  mutate(perc_coac = replace_na(perc_coac, 0))

ool17_vec <- c(0,1,10,20,30,40,50,60,70,80,90,100)
ool17_df <- data.frame(perc_coac=character(),
                 perc_transcripts=numeric(),
                 label = character(),
                 stringsAsFactors=FALSE)
# transcripts in 0 condensates
ool17_df[1,1] <- paste(ool17_vec[1], "%")
ool17_df[1,2] <- ool17_all_input_rnas.3 %>% filter(perc_coac <= ool17_vec[1]) %>% summarise(dat= sum(perc_transcripts)) %>% dplyr::pull(dat)
ool17_df[1,3] <- paste(round(ool17_df[1,2]), "%")

x = 1
for (i in c(2:length(ool17_vec))){
  ool17_df[x+1,1] <- paste(paste(ool17_vec[x], ool17_vec[x+1], sep = "-"), "%")
  ool17_df[x+1,2] <- ool17_all_input_rnas.3 %>% filter(perc_coac > ool17_vec[x] & perc_coac < ool17_vec[x+1]) %>% summarise(dat= sum(perc_transcripts)) %>% dplyr::pull(dat)
  ool17_df[x+1,3] <- paste(round(ool17_df[x,2],digits = 1), "%")
  x = x + 1
}

ool17_df <- ool17_df[c(1:12),]


#
# ---- OOL18 Data ------------------------------------
#

# all coacervate rnas
ool18_all_coac_rnas <- master %>%  
  filter(experiment == "ool18") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(num_coac = n()) %>% 
  mutate(perc_coac = num_coac/max(num_coac)*100) %>% 
  arrange(desc(num_coac))

# input rnas + their presence in x # of condensates
ool18_all_input_rnas <- master %>% 
  filter(experiment == "ool18_input") %>% 
  filter(tpm != 0) %>% 
  left_join(.,ool18_all_coac_rnas, by = "target_id") %>% 
  mutate(num_coac = replace_na(num_coac,0)) %>% 
  dplyr::select(target_id, num_coac, perc_coac) %>% 
  arrange(desc(num_coac)) 

# How many input RNAs are in how many condensates?
ool18_all_input_rnas.2 <- ool18_all_input_rnas %>% 
  group_by(num_coac) %>% 
  summarise(num_transcripts = n())

# As in 'all_input_rnas.2' but in %
ool18_all_input_rnas.3 <- ool18_all_input_rnas %>% 
  left_join(.,ool18_all_input_rnas.2, by = "num_coac") %>% 
  mutate(perc_transcripts = num_transcripts/nrow(.)*100) %>% 
  dplyr::select(perc_coac, perc_transcripts) %>% distinct() %>% 
  mutate(perc_coac = replace_na(perc_coac, 0))

ool18_vec <- c(0,1,10,20,30,40,50,60,70,80,90,100)
ool18_df <- data.frame(perc_coac=character(),
                       perc_transcripts=numeric(),
                       label = character(),
                       stringsAsFactors=FALSE)
# transcripts in 0 condensates
ool18_df[1,1] <- paste(ool18_vec[1], "%")
ool18_df[1,2] <- ool18_all_input_rnas.3 %>% filter(perc_coac <= ool18_vec[1]) %>% summarise(dat= sum(perc_transcripts)) %>% dplyr::pull(dat)
ool18_df[1,3] <- paste(round(ool18_df[1,2]), "%")

x = 1
for (i in c(2:length(ool18_vec))){
  ool18_df[x+1,1] <- paste(paste(ool18_vec[x], ool18_vec[x+1], sep = "-"), "%")
  ool18_df[x+1,2] <- ool18_all_input_rnas.3 %>% filter(perc_coac > ool18_vec[x] & perc_coac < ool18_vec[x+1]) %>% summarise(dat= sum(perc_transcripts)) %>% dplyr::pull(dat)
  ool18_df[x+1,3] <- paste(round(ool18_df[x,2],digits = 1), "%")
  x = x + 1
}

ool18_df <- ool18_df[c(1:12),]


#
# ---- Ave Data ------------------------------------
#

ave_df <- merge(ool17_df,ool18_df, by = "perc_coac")
ave_df <- ave_df %>% mutate(perc_transcripts = (perc_transcripts.x+perc_transcripts.y)/2) %>% select(perc_coac, perc_transcripts)
```

## Figure 2a

```{r}
comb_count <- left_join(ool18_all_input_rnas, ool17_all_input_rnas, by = "target_id") %>% drop_na()

s1b_model <- lm(perc_coac.x ~ perc_coac.y, comb_count) 
s1b_r2 <- as.character(paste("R^2 =", round(summary(s1b_model)$r.squared, 3), sep = " "))
s1b_rho <- paste("r = ", round(cor(comb_count$perc_coac.x,comb_count$perc_coac.y),2), sep = "")

fig2b <- ggplot(data = comb_count, 
       aes(x = perc_coac.x , y = perc_coac.y)) +
  geom_point(size = 3, alpha = .7, shape = 21) +
  geom_density2d(binwidth = 0.0004, colour = "blue", size = .8) +
  annotate(geom = 'text', label = s1b_rho, x = 75, y = min(comb_count$perc_coac.y), hjust = 0, vjust = -1.5, size = 10) +
  annotate(geom = 'text', label = "x = y", x = 75, y = min(comb_count$perc_coac.y), hjust = 0, vjust = -3, size = 10, col = "red") +
  geom_abline(intercept = 0, slope = 1, col = "red", size = 1) +
  labs(x = "Transcripts in x% coacervates\nExperiment A", y = "Transcripts in x% coacervates\nExperiment B")

plot(fig2b)
```

## Figure 2a - 2

```{r}
# --- > 90 % ------------------------

# popular input rnas + their presence in x # of condensates
ninty_coac_ool17 <- ool17_all_input_rnas %>%
  filter(perc_coac > 90) %>% 
  dplyr::select(target_id)

# popular input rnas + their presence in x # of condensates
ninty_coac_ool18 <- ool18_all_input_rnas %>% 
  filter(perc_coac > 90) %>% 
  dplyr::select(target_id)

fig2b_2 <- draw.pairwise.venn(area1 = nrow(ninty_coac_ool17), area2 = nrow(ninty_coac_ool18), 
                   cross.area = length(intersect(ninty_coac_ool17$target_id,ninty_coac_ool18$target_id)), 
                   fill = c("#9E0142","#9E0142"), cex = 0, col = "white")
```

## Figure 2b

```{r}
ool17_ave_tpm <- master %>%  
  filter(experiment == "ool17") %>%  
  filter(tpm != 0) %>%  
  group_by(target_id) %>%  
  summarise(ave_tpm = mean(log2_tpm), CV = sd(log2_tpm)/mean(log2_tpm))

ool18_ave_tpm <- master %>%
  filter(experiment == "ool18") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(ave_tpm = mean(log2_tpm), CV = sd(log2_tpm)/mean(log2_tpm))

comb_ave_tpm <- left_join(ool17_ave_tpm, ool18_ave_tpm, by = "target_id") %>% drop_na()

s2c_model <- lm(ave_tpm.x ~ ave_tpm.y, comb_ave_tpm) 
s2c_r2 <- as.character(paste("R^2 =", round(summary(s2c_model)$r.squared, 3), sep = " "))
s2c_rho <- paste("r = ", round(cor(comb_ave_tpm$ave_tpm.x,comb_ave_tpm$ave_tpm.y),2), sep = "")

# Correlation of RNA abundance
fig2c <- ggplot(data = left_join(ool17_ave_tpm, ool18_ave_tpm, by = "target_id"), aes(x = ave_tpm.x , y = ave_tpm.y)) +
  geom_point(size = 3, alpha = .7, shape = 21) +
  annotate(geom = 'text', label = s2c_rho, x = 12, y = .7, hjust = -.0, vjust = 0, size = 10) +
  annotate(geom = 'text', label = "x = y", x = 12, y = .7, hjust = -.0, vjust = -1.5, size = 10, col = "red") +
  geom_density2d(binwidth = 0.002, colour = "blue", size = .8) +
  geom_abline(intercept = 0, slope = 1, col = "red", size = 1) +
  labs(x = "Ave. RNA amount in coacervates\nlog2(TPM) in Experiment A", y = "Ave. RNA amount in coacervates\nlog2(TPM) in Experiment B") +
  lims(y = c(0,16), x = c(0,16))

plot(fig2c)
```

## Figure 2c

```{r}
# ---- Plot data ----

# define colors:
farben <- rev(brewer.pal(11,"Spectral"))
farben <- c("grey", farben)

ave_df_a <- ggplot(data=ave_df, aes(x = "1", y = perc_transcripts, fill=as.factor(perc_coac))) +
  geom_bar(stat = "identity", color = "white", position = position_fill(reverse = TRUE)) +
  scale_fill_manual(values = farben) +
  coord_polar("y", start = 1.7)+
  theme_void() +
  labs(fill = "Transcripts found in how many coacervates ?", y = "Fraction of all transcripts") +
  theme(legend.position="top", legend.title = element_text(size=18), legend.text = element_text(size=16)) +
  guides(fill = guide_legend(title.position = "top"))

ave_df_b <- ggplot(data=ave_df[c(5:11),], aes(x = "", y = perc_transcripts, fill=perc_coac)) +
  geom_bar(stat = "identity", color = "white", position = position_fill(reverse = TRUE)) +
  scale_fill_manual(values = farben[c(6:12)]) +
  theme_void() +
  theme(legend.position = "none")

fig2a <- plot_grid(ave_df_a,ave_df_b, ncol = 2, rel_widths = c(3,1))
plot(fig2a)
```