---
title: "ool44: Quantification of motif enrichment by microscopy"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.width= 12, fig.height=7)
```

```{r}
library(tidyverse)
library(data.table)
library(mgcv)
library(seqinr)

theme_set(theme_classic(base_size=22))
```

The raw data and original analysis can be found in:

/Users/damian_wollny/PD/Data/OoL/44_partition_coeff/

```{r}
# open data from image quantification

img_count <- read.csv(file = "~/PD/Data/OoL/44_partition_coeff/quantification.csv", sep = ";") %>% select(-n) %>% as.tbl()

# plot

quant_scope_data <- img_count %>% 
  group_by(sample) %>% 
  mutate(part_coeff = ave/mean(ave[background == "yes"]),
         mean_part_coef = mean(part_coeff)) %>% 
  ungroup() %>% 
  filter(background == "no",
       grepl(pattern = "PDDA.*", x = .$sample)) %>%
  mutate(name = if_else(sample == "PDDA_ds_2uM", "Motif1 + RC",
                        if_else(sample == "PDDA_motif_2uM", "Motif1", "Motif2"))) %>% 
  mutate(ds = if_else(grepl(pattern = ".*_ds.*", x = .$sample), "yes", "no")) %>%  
  ggplot(aes(x =reorder(name, -ave, FUN = median), y = ave, colour = ds)) +
  geom_boxplot() +
  geom_point(size = 4, alpha = .5) +
  scale_color_manual(values = c("#9E0142", "darkgrey"), 
                   breaks = c("yes", "no"),
                   labels = c("Double stranded", "Single stranded")) +
  labs(y = "Fluorescence Intensity [AU]", x = "") +
  theme(legend.title = element_blank(), 
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.title.x = element_blank(),
      legend.position = "right")
plot(quant_scope_data)  

print(paste("partition coefficient (ds) =", img_count %>% 
  group_by(sample) %>% 
  mutate(part_coeff = ave/mean(ave[background == "yes"]),
         mean_part_coef = mean(part_coeff)) %>% 
    filter(sample == "PDDA_ds_2uM") %>% 
    pull(mean_part_coef) %>% 
    unique() %>% 
    round(.,2)))  
```

```{r}
ggsave(quant_scope_data, file="~/PD/Data/OoL/43_Draft_5/_s_fig6/s_fig6_scope_quant.pdf", width = 6, height = 6, device = "pdf")
```

