---
title: "Supplementary Figure 10"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = FALSE, message = FALSE)
```

```{r}
# Setup
library(tidyverse)
library(circlize)
library(RColorBrewer)

theme_set(theme_classic(base_size=24))

# --- colors for this figure

# color: "spectral"
fig3_cols <- brewer.pal(n = 10, name = "Spectral")
fig3_cols[5] <- "#fdcc3f"
fig3_cols[6] <- "#d5ee52"

# function to make colors transparent
makeTransparent = function(..., alpha=0.5) {
  if(alpha<0 | alpha>1) stop("alpha must be between 0 and 1")
  alpha = floor(255*alpha)  
  newColor = col2rgb(col=unlist(list(...)), alpha=FALSE)
  .makeTransparent = function(col, alpha) {
    rgb(red=col[1], green=col[2], blue=col[3], alpha=alpha, maxColorValue=255)
  }
  newColor = apply(newColor, 2, .makeTransparent, alpha=alpha)
  return(newColor)
}

```

<style type="text/css">

body, td {
   font-size: 18px;
}
</style>

## Figure S10a

```{r, fig.width=9}
# Get parsed meme data from random transcripts
enr_trans <- read.csv(file = "./_meme/enr_parsed_meme_output.csv")
# reorder factor levels according to MEME enrichment score
level_order <- c(3,5,6,1,9,4,10,7,2,8)
enr_trans$motif <- factor(enr_trans$motif,levels = levels(enr_trans$motif)[level_order])
enr_trans <- enr_trans %>% mutate(motif_rank = as.integer((enr_trans$motif)))

# Calculate size of the gaps between all motifs for each transcript
enr_trans_dist <- enr_trans %>% 
  group_by(transcript) %>% 
  arrange(start) %>% 
  mutate(dist = start - lag(start)) %>% # distance to previous motif
  mutate(previous_motif = lag(motif_rank)) %>% # what is the previous motif
  dplyr::filter(!is.na(dist))
# New facet label names for motif_rank variables
facet.labs.r <- paste("Motif: ", enr_trans_dist$motif_rank)
names(facet.labs.r) <- c(enr_trans_dist$motif_rank)

### ENRICHED: distances of the motifs to the previous motif across transcripts:
supp_fig <- enr_trans_dist %>% ggplot(aes(dist)) +
  geom_density(aes(color = as.factor(motif_rank), fill = as.factor(motif_rank))) +
  facet_wrap(.~motif_rank, scales = "free_y", nrow = 2, labeller = labeller(motif_rank = facet.labs.r)) +
  scale_x_log10() +  
  scale_color_manual(values = fig3_cols) +
  scale_fill_manual(values = makeTransparent(fig3_cols)) +
  labs(x = "Distance to closest previous motif [bp]") +
  theme(legend.position = "none", strip.text.x = element_text(size = 16), axis.text.x = element_text(size = 18, angle = 45, vjust = .6))
plot(supp_fig)
```

## Figure S10a

```{r, fig.width=9}
s_fig4_facet <- fig3_cols
s_fig4_facet[c(2,3,5,7,8,10)] <- "white"
trans_s_fig4_cols <- makeTransparent(fig3_cols)
s_fig4_links <- trans_s_fig4_cols

# df for circos.link() for interesting motifs
circos_links_df <- enr_trans_dist %>% 
  group_by(motif_rank, previous_motif) %>% 
  summarise(count = n()) %>% 
  filter(motif_rank %in% c(1,4,6,9)) %>% 
  mutate(perc = count * 1000 / sum(count)) %>% 
  arrange(perc) %>% 
  mutate(end = cumsum(perc)) %>% 
  mutate(start = lag(end, default = 0)) %>% 
  as.data.frame()

# --- plot ---
# first track:
circos.clear()
circos.par(track.height	= .08)
circos.initialize(factors = as.factor(enr_trans_dist$motif_rank), x = enr_trans_dist$dist, xlim = c(0,1000))
circos.trackPlotRegion(factors = as.factor(enr_trans_dist$motif_rank), ylim = c(0,1), bg.col = s_fig4_facet, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ycenter, 
              CELL_META$sector.index, facing = "downward", cex = 1.5)
})
# links
for (i in c(1:nrow(circos_links_df))){
  circos.link(sector.index1 = circos_links_df[i,1], point1 = c(circos_links_df[i,5],circos_links_df[i,6]), sector.index2 = circos_links_df[i,2], point2 = 500, col = s_fig4_links[circos_links_df[i,1]])
}
```



## Figure S10c

```{r, fig.width=9}
# Get parsed meme data from random transcripts
random_trans <- read.csv(file = "./_meme/rand_parsed_meme_output.csv")
# reorder factor levels according to MEME enrichment score
level_order <- c(5,9,7,10,4,8,6,2,3,1)
random_trans$motif <- factor(random_trans$motif,levels = levels(random_trans$motif)[level_order])
random_trans <- random_trans %>% mutate(motif_rank = as.integer((random_trans$motif)))

# Calculate size of the gaps between all motifs for each transcript
random_trans_dist <- random_trans %>% 
  group_by(transcript) %>% 
  arrange(start) %>% 
  mutate(dist = start - lag(start)) %>% # distance to previous motif
  mutate(previous_motif = lag(motif_rank)) %>% # what is the previous motif
  filter(!is.na(dist))
# New facet label names for motif_rank variables
facet.labs.r <- paste("Motif: ", random_trans_dist$motif_rank)
names(facet.labs.r) <- c(random_trans_dist$motif_rank)

### RANDOM: distances of the motifs to the previous motif across transcripts:
supp_fig <- random_trans_dist %>% ggplot(aes(dist)) +
  geom_density(aes(color = as.factor(motif_rank), fill = as.factor(motif_rank))) +
  facet_wrap(.~motif_rank, scales = "free_y", nrow = 2, labeller = labeller(motif_rank = facet.labs.r)) +
  scale_x_log10() +  
  scale_color_manual(values = fig3_cols) +
  scale_fill_manual(values = makeTransparent(fig3_cols)) +
  labs(x = "Distance to closest previous motif [bp]") +
  theme(legend.position = "none", strip.text.x = element_text(size = 16), axis.text.x = element_text(size = 18, angle = 45, vjust = .6))
plot(supp_fig)
```

## Figure S10d

```{r, fig.width=9}


s_fig4_facet <- fig3_cols
trans_s_fig4_cols <- makeTransparent(fig3_cols)
s_fig4_links <- trans_s_fig4_cols

# df for circos.link() for interesting motifs
circos_links_df <- random_trans_dist %>% 
  group_by(motif_rank, previous_motif) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count * 1000 / sum(count)) %>% 
  arrange(perc) %>% 
  mutate(end = cumsum(perc)) %>% 
  mutate(start = lag(end, default = 0)) %>% 
  as.data.frame()

# --- plot ---
# first track:
circos.clear()
circos.par(track.height	= .08)
circos.initialize(factors = as.factor(random_trans_dist$motif_rank), x = random_trans_dist$dist, xlim = c(0,1000))
circos.trackPlotRegion(factors = as.factor(random_trans_dist$motif_rank), ylim = c(0,1), bg.col = s_fig4_facet, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ycenter, 
              CELL_META$sector.index, facing = "downward", cex = 1.5)
})
# links
for (i in c(1:nrow(circos_links_df))){
  circos.link(sector.index1 = circos_links_df[i,1], point1 = c(circos_links_df[i,5],circos_links_df[i,6]), sector.index2 = circos_links_df[i,2], point2 = 500, col = s_fig4_links[circos_links_df[i,1]])
}
```

