---
title: "Figure 3 - Draft"
author: "Damian Wollny"
output:
  html_document:
    theme: paper
    df_print: kable
date: '`r format(Sys.Date(), "%B %d, %Y")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = FALSE, message = FALSE)
options(width = 12)
```

```{r}
# Setup
library(tidyverse)
library(Rmpfr)
library(mgcv)
library(circlize)
library(RColorBrewer)

theme_set(theme_classic(base_size=24))
setwd(dir = "~/PD/Data/OoL/33_Draft_3/_fig3/")

# --- colors for this figure

# color: "spectral"
fig3_cols <- brewer.pal(n = 10, name = "Spectral")
fig3_cols[5] <- "#fdcc3f"
fig3_cols[6] <- "#d5ee52"

# function to make colors transparent
makeTransparent = function(..., alpha=0.5) {
  if(alpha<0 | alpha>1) stop("alpha must be between 0 and 1")
  alpha = floor(255*alpha)  
  newColor = col2rgb(col=unlist(list(...)), alpha=FALSE)
  .makeTransparent = function(col, alpha) {
    rgb(red=col[1], green=col[2], blue=col[3], alpha=alpha, maxColorValue=255)
  }
  newColor = apply(newColor, 2, .makeTransparent, alpha=alpha)
  return(newColor)
}

```

<style type="text/css">

body, td {
   font-size: 18px;
}
</style>

### Input:

Cleaned up integrated data all experiments:

`/Users/damian_wollny/PD/Data/OoL/19.1_Draft_2/Generate_input/draft2_input.RDS`

```{r}
master <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/19.1_Draft_2/Generate_input/draft2_input.RDS")
```

## Figure 3A

```{r}
# --- OOL17 replicate ------------------

ool17_input_tpm <- master %>%
  filter(experiment == "ool17_input") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(input_tpm = log2_tpm)

ool17_bens_plot <- master %>% 
  filter(tpm != 0) %>% 
  filter(experiment == "ool17") %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  left_join(ool17_input_tpm, ., by="target_id") %>% 
  mutate(count = replace(count, which(is.na(count)), 0)) %>% # include all transcripts that are found in 0 coac
  mutate(percent = count*100/max(count)) 

# --- OOL18 replicate ------------------

ool18_input_tpm <- master %>%
  filter(experiment == "ool18_input") %>% 
  filter(tpm != 0) %>% 
  group_by(target_id) %>% 
  summarise(input_tpm = log2_tpm)

ool18_bens_plot <- master %>% 
  filter(tpm != 0) %>% 
  filter(experiment == "ool18") %>% 
  group_by(target_id) %>% 
  summarise(count = n()) %>% 
  left_join(ool18_input_tpm, ., by="target_id") %>% 
  mutate(count = replace(count, which(is.na(count)), 0)) %>% # include all transcripts that are found in 0 coac
  mutate(percent = count*100/max(count)) 

# --- Ave ------------------

# Filter all transcripts that are present in both replicate experiments
ave_bens_plot <- inner_join(ool17_bens_plot, ool18_bens_plot, by = "target_id")

# Calc ave(input_tpm) and ave(percent) for each transcript
ave_bens_plot <- ave_bens_plot %>% 
  mutate(input_tpm = (input_tpm.x+input_tpm.y)/2) %>% 
  mutate(percent = (percent.x+percent.y)/2) %>% 
  select(target_id, input_tpm, percent) 

# get residuals from model describing data in bens_plot
ave_bens_plot_model <- gam(percent ~ s(input_tpm, bs = "cs"), data = ave_bens_plot)
ave_bens_plot <- ave_bens_plot %>% mutate(residuals = ave_bens_plot_model$residuals)

# plot
fig3a <- ggplot(data = ave_bens_plot, aes(x = input_tpm, y = percent)) +
  geom_point(size = 3, alpha = .7, shape = 21) +
  geom_point(data = ave_bens_plot %>% filter(residuals > 30), color = fig3_cols[1], size = 4, alpha = 0.4) +
  stat_smooth(col = "indianred2") +
  scale_y_continuous(limits = c(0,105)) +
  labs(x = "Input mRNA amount\nlog2(TPM)", y = "Detected in x\ncondensates [%]")
plot(fig3a)
ggsave(fig3a, file="./fig3a.pdf", width = 6, height = 6, device = "pdf")
```

## Figure 3B

```{r}
# Several tricks had to be used to work with very small numbers
# 1.) colClasses of the e_values had to be converted to a character when reading csv
# 2.) mpfr function from the Rmpfr package needed to be used to read the small numbers. Takes char as input
# 3.) mpfr output was log converted and transformed into numeric

test <- read.csv(file = "/Users/damian_wollny/PD/Data/OoL/18.2_integrative_analysis/_1_comparison/_even_newer_meme_analysis/_ave_pdda_coac/_meme_output/resids/meme.csv", colClasses = c("e_value" = "character"))
test$e_value <- as.numeric(log(mpfr(test$e_value)))
test$e_value <- test$e_value*-1

# convert 'motif' column to factor and reorder levels according to e_value (for plotting)
test$motif <- factor(test$motif, levels = reorder(test$motif,test$e_value))

# define colors (for plottting)
fig3b1_cols = makeTransparent(fig3_cols, alpha = 0.7)
# plot:

fig3b1 <- ggplot(data = test, aes(x=motif, y=e_value, fill = motif)) +
  geom_bar(stat = "identity", color = "black") +
  scale_y_continuous(expand = c(0,0), limits = c(0,1300)) +
  scale_fill_manual(values=fig3b1_cols) +
  scale_x_discrete(breaks=c(as.character(test$motif)), labels=c(1:10)) +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_text(angle = 90, hjust = .5, size = 24))
ggsave(fig3b1, file="./fig3b1.pdf", width = 6, height = 6, device = "pdf")

fig3b1_axis <- ggplot(data = test, aes(x=motif, y=e_value, fill = motif)) +
  geom_bar(stat = "identity", color = "black") +
  scale_y_continuous(expand = c(0,0), limits = c(0,1300)) +
  scale_fill_manual(values=fig3b1_cols) +
  scale_x_discrete(breaks=c(as.character(test$motif)), labels=c(1:10)) +
  theme(legend.position = "none") +
  labs(x = "Motifs from\nenriched transcripts", y = "Motif enrichment")
plot(fig3b1_axis)


# --- meme output for random transcripts ---------

meme_random <- read.csv(file = "/Users/damian_wollny/PD/Data/OoL/18.2_integrative_analysis/_1_comparison/_even_newer_meme_analysis/_ave_pdda_coac/_meme_output/_random_transcripts/resids/meme.csv", colClasses = c("e_value" = "character"))
meme_random$e_value <- as.numeric(log(mpfr(meme_random$e_value)))
meme_random$e_value <- meme_random$e_value*-1

# convert 'motif' column to factor and reorder levels according to e_value (for plotting)
meme_random$motif <- factor(meme_random$motif, levels = reorder(meme_random$motif,meme_random$e_value))

# define colors (for plotting)
fig3b2_cols = rep("grey",10)

# plot:
fig3b2 <- ggplot(data = meme_random, aes(x=motif, y=e_value, fill = motif)) +
  geom_bar(stat = "identity", color = "black") +
  scale_y_continuous(expand = c(0,0), limits = c(0,1300)) +
  scale_fill_manual(values=fig3b2_cols) +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_text(angle = 90, hjust = .5, size = 24))
ggsave(fig3b2, file="./fig3b2.pdf", width = 6, height = 6, device = "pdf")

fig3b2_axis <- ggplot(data = meme_random, aes(x=motif, y=e_value, fill = motif)) +
  geom_bar(stat = "identity", color = "black") +
  scale_y_continuous(expand = c(0,0), limits = c(0,1300)) +
  scale_fill_manual(values=fig3b2_cols) +
  scale_x_discrete(breaks=c(as.character(meme_random$motif)), labels=c(1:10)) +
  theme(legend.position = "none") +
  labs(x = "Motifs from\nrandom transcripts", y = "Motif enrichment")
plot(fig3b2_axis)

```

## Figure 3C

```{r}
# read mast analysis for ave_pdda_M1 using e_val cutoff 0.05
motif1_test <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/18.2_integrative_analysis/_4_motif_modelling/_ave_pdda_mast_analysis/M1/ave_pdda_m1.RDS")
# read mast analysis for ave_pdda_random using e_val cutoff 0.05
motif1_test.1 <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/18.2_integrative_analysis/_4_motif_modelling/_ave_pdda_mast_analysis/random/ave_pdda_random.RDS")


fig3c <- ave_bens_plot %>% inner_join(.,motif1_test.1, by = "target_id") %>% 
  mutate(index = if_else(count == 2, 3, if_else(strand == "+", 1, 2))) %>% 
  ggplot(aes(x = percent, color = as.factor(index))) +
  geom_density(aes(fill = as.factor(index)), alpha = 0.2, size = .7) +
  geom_density(data = ave_bens_plot %>% anti_join(.,motif1_test.1, by = "target_id") %>% mutate(index = 0), aes(fill = as.factor(index)), alpha = 0.2, size = .7) +
  scale_color_manual(values=c( "darkgrey", fig3_cols[1], fig3_cols[2], "black"), 
                     breaks=c("0","1", "2", "3"),
                     labels=c("No Motif", "Motif: 1", "Motif: 2", "Motif: 1 + 2")) +
  scale_fill_manual(values = c("white", "white", "white", "grey")) +
  scale_x_continuous(trans = "log10") +
  labs(x = "Detected in x\ncondensates [%]") +
  theme(legend.title = element_blank(), legend.position = c(0.25,0.91)) +
  guides(fill=FALSE)

plot(fig3c)
ggsave(fig3c, file="./fig3c.pdf", width = 6, height = 6)
```

## Figure 3D

```{r, fig.width=9}
comb <- readRDS(file = "/Users/damian_wollny/PD/Data/OoL/18.2_integrative_analysis/_5_pairwise_alignment/_Smith_Watermann/_ave_pdda/_bens_penalty/_output/comb_data.RDS")

# convert 'transcripts' col to factor and change level for facet labels
comb$transcripts <- as.factor(comb$transcripts)
levels(comb$transcripts) <- c("enriched vs enriched", "enriched vs random", "random vs random")

# histogram: distribution of SW-scores
fig3d <- ggplot(data = comb, aes(value)) +
  geom_histogram(aes(fill = transcripts), bins = 50) +
  facet_grid(. ~ transcripts) +
  scale_fill_manual(values = c(fig3_cols[1], "darkgrey", "darkgrey")) +
  scale_y_continuous(trans = "log10", expand = c(0,0)) +
  xlim(c(0,2100)) +
  geom_segment(aes(x = 510, y = 1, xend = 510, yend = 1e4), linetype = 2, color = "black") +
  labs(x = "RNA-RNA complementarity score") +
  theme(legend.position = "none", strip.text.x = element_text(size = 18), 
        axis.text.x = element_text(size = 18, angle = 45, vjust = .6))
plot(fig3d)
ggsave(fig3d, file="./fig3d.pdf", width = 10, height = 6)
```

## Figure 3E
```{r, fig.width=9}
# Get parsed meme data from enriched transcripts
enriched_trans <- read.csv(file = "~/PD/Data/OoL/18.2_integrative_analysis/_1_comparison/_even_newer_meme_analysis/_ave_pdda_coac/_meme_output/resids/parsed_meme_output.csv")
# reorder factor levels according to MEME enrichment score
level_order <- c(3,5,6,1,9,4,10,7,2,8)
enriched_trans$motif <- factor(enriched_trans$motif,levels = levels(enriched_trans$motif)[level_order])
enriched_trans <- enriched_trans %>% mutate(motif_rank = as.integer((enriched_trans$motif)))

# Get parsed meme data from random transcripts
random_trans <- read.csv(file = "~/PD/Data/OoL/18.2_integrative_analysis/_1_comparison/_even_newer_meme_analysis/_ave_pdda_coac/_meme_output/_random_transcripts/resids/parsed_meme_output.csv")
# reorder factor levels according to MEME enrichment score
level_order <- c(5,9,7,10,4,8,6,2,3,1)
random_trans$motif <- factor(random_trans$motif,levels = levels(random_trans$motif)[level_order])
random_trans <- random_trans %>% mutate(motif_rank = as.integer((random_trans$motif)))

# Calculate size of the gaps between all motifs for each transcript
enriched_trans_dist <- enriched_trans %>% 
  group_by(transcript) %>% 
  arrange(start) %>% 
  mutate(dist = start - lag(start)) %>% # distance to previous motif
  mutate(previous_motif = lag(motif_rank)) %>% # what is the previous motif
  filter(!is.na(dist))

random_trans_dist <- random_trans %>% 
  group_by(transcript) %>% 
  arrange(start) %>% 
  mutate(dist = start - lag(start)) %>% # distance to previous motif
  mutate(previous_motif = lag(motif_rank)) %>% # what is the previous motif
  filter(!is.na(dist))

# New facet label names for motif_rank variables
facet.labs.e <- paste("Motif: ", enriched_trans_dist$motif_rank)
names(facet.labs.e) <- c(enriched_trans_dist$motif_rank)
facet.labs.r <- paste("Motif: ", random_trans_dist$motif_rank)
names(facet.labs.r) <- c(random_trans_dist$motif_rank)

# define colors for fig3e
fig3e_cols <- fig3_cols
fig3e_fill <- fig3_cols
fig3e_fill[c(2,3,5,7,8,10)] <- "white"

### Enriched: distances of the motifs to the previous motif across transcripts:
# prelim plot fig3e
p <- enriched_trans_dist %>% ggplot(aes(dist)) +
  geom_density(aes(color = as.factor(motif_rank), fill = as.factor(motif_rank))) +
  facet_wrap(.~motif_rank, scales = "free_y", nrow = 2, labeller = labeller(motif_rank = facet.labs.e)) +
  scale_x_log10() +
  scale_color_manual(values = fig3e_cols) +
  scale_fill_manual(values = makeTransparent(fig3e_cols)) +
  labs(x = "Distance to closest 5´ motif [bp]") +
  theme(legend.position = "none", strip.text.x = element_text(size = 18),
        axis.text.x = element_text(size = 18, angle = 45, vjust = .6))

# conditional facet strip background colors
g <- ggplot_gtable(ggplot_build(p))
striprt <- which( grepl('strip-r', g$layout$name) | grepl('strip-t', g$layout$name) )
fills <- makeTransparent(fig3e_fill[c(6:10, 1:5)])
k <- 1
for (i in striprt) {
  j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

# final plot fig3e
fig3e <- g
plot(fig3e)
ggsave(fig3e, file="./fig3e.pdf", width = 12, height = 6)
```

## Figure 3F
```{r}
fig3f_facet <- fig3_cols
fig3f_facet[c(2,3,5,7,8,10)] <- "white"
trans_fig3f_cols <- makeTransparent(fig3_cols)
fig3f_links <- trans_fig3f_cols

# df for circos.link() for interesting motifs
circos_links_df <- enriched_trans_dist %>% 
  group_by(motif_rank, previous_motif) %>% 
  summarise(count = n()) %>% 
  filter(motif_rank %in% c(1,4,6,9)) %>% 
  mutate(perc = count * 1000 / sum(count)) %>% 
  arrange(perc) %>% 
  mutate(end = cumsum(perc)) %>% 
  mutate(start = lag(end, default = 0)) %>% 
  as.data.frame()

# --- plot ---
# first track:
circos.clear()
circos.par(track.height	= .08)
circos.initialize(factors = as.factor(enriched_trans_dist$motif_rank), x = enriched_trans_dist$dist, xlim = c(0,1000))
circos.trackPlotRegion(factors = as.factor(enriched_trans_dist$motif_rank), ylim = c(0,2), bg.col = fig3f_facet, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ycenter, 
              CELL_META$sector.index, facing = "downward", cex = 1.5)
})
# links
for (i in c(1:nrow(circos_links_df))){
  circos.link(sector.index1 = circos_links_df[i,1], point1 = c(circos_links_df[i,5],circos_links_df[i,6]), sector.index2 = circos_links_df[i,2], point2 = 500, col = fig3f_links[circos_links_df[i,1]])
}
```

```{r, echo = F}
# export circos plot:
pdf("./fig3f.pdf") 
# first track:
circos.clear()
circos.par(track.height	= .08)
circos.initialize(factors = as.factor(enriched_trans_dist$motif_rank), x = enriched_trans_dist$dist, xlim = c(0,1000))
circos.trackPlotRegion(factors = as.factor(enriched_trans_dist$motif_rank), ylim = c(0,1), bg.col = fig3f_facet, panel.fun = function(x, y) {
  circos.text(CELL_META$xcenter, CELL_META$ycenter, 
              CELL_META$sector.index, facing = "downward", cex = 1.5)
})
# links
for (i in c(1:nrow(circos_links_df))){
  circos.link(sector.index1 = circos_links_df[i,1], point1 = c(circos_links_df[i,5],circos_links_df[i,6]), sector.index2 = circos_links_df[i,2], point2 = 500, col = fig3f_links[circos_links_df[i,1]])
}
dev.off()
```

